### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by kashif612** [CryceTruly/truly-contacts-youtube#2]
I have the [api](https://truly-contacts.herokuapp.com/api) this is open to use or restricted because i am stuck in error or i have to create own api address on swagger
[Mon Dec 27 2021 22:26:07.608]  BUNDLE  ./index.js

error: TypeError: Cannot read properties of undefined (reading 'reduce')
    at resolveDependencies (C:\Users\dell\Desktop\contact\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at C:\Users\dell\Desktop\contact\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\dell\Desktop\contact\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (C:\Users\dell\Desktop\contact\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by kashif612** [comment]
sorry according to your video i am follow up your video you are using own api address of your api(https://truly-contacts.herokuapp.com/api) so can i used this api address to my project or not or i have to create my own api at swagger
